export type Key<T extends string | number | Date> = T;

export type JWT<T extends object> = T;

export type { ApiUtil, ConsumptionUtil } from "./consumption-apis/helpers";
export {
  ClickHouseByteSize,
  ClickHouseCodec,
  ClickHouseDecimal,
  ClickHouseDefault,
  ClickHouseFixedStringSize,
  ClickHouseFloat,
  ClickHouseInt,
  ClickHouseJson,
  ClickHouseMaterialized,
  ClickHouseNamedTuple,
  ClickHousePrecision,
  ClickHouseTTL,
  // Added friendly aliases and numeric helpers
  DateTime,
  DateTime64,
  DateTime64String,
  DateTimeString,
  Decimal,
  FixedString,
  Float32,
  Float64,
  Int8,
  Int16,
  Int32,
  Int64,
  LowCardinality,
  UInt8,
  UInt16,
  UInt32,
  UInt64,
  WithDefault,
} from "./dataModels/types";
export {
  Aggregated,
  Api,
  ApiConfig,
  ClickHouseEngines,
  ConsumptionApi,
  DeadLetter,
  DeadLetterModel,
  DeadLetterQueue,
  EgressConfig,
  ETLPipeline,
  ETLPipelineConfig,
  FrameworkApp,
  getApi,
  getApis,
  getIngestApi,
  getIngestApis,
  getMaterializedView,
  getMaterializedViews,
  getSqlResource,
  getSqlResources,
  getStream,
  getStreams,
  getTable,
  // Registry functions
  getTables,
  getView,
  getViews,
  getWebApp,
  getWebApps,
  getWorkflow,
  getWorkflows,
  IngestApi,
  IngestConfig,
  IngestPipeline,
  LifeCycle,
  MaterializedView,
  OlapConfig,
  OlapTable,
  S3QueueTableSettings,
  SimpleAggregated,
  SqlResource,
  Stream,
  StreamConfig,
  Task,
  View,
  WebApp,
  WebAppConfig,
  WebAppHandler,
  Workflow,
} from "./dmv2";

export * from "./sqlHelpers";
