export type Key<T extends string | number | Date> = T;

export type JWT<T extends object> = T;

export {
  ClickHouseEngines,
  Aggregated,
  SimpleAggregated,
  OlapTable,
  OlapConfig,
  S3QueueTableSettings,
  Stream,
  StreamConfig,
  DeadLetterModel,
  DeadLetter,
  DeadLetterQueue,
  IngestApi,
  IngestConfig,
  Api,
  ApiConfig,
  ConsumptionApi,
  EgressConfig,
  IngestPipeline,
  SqlResource,
  View,
  MaterializedView,
  Task,
  Workflow,
  ETLPipeline,
  ETLPipelineConfig,
  LifeCycle,
  WebApp,
  WebAppConfig,
  WebAppHandler,
  FrameworkApp,
  // Registry functions
  getTables,
  getTable,
  getStreams,
  getStream,
  getIngestApis,
  getIngestApi,
  getApis,
  getApi,
  getSqlResources,
  getSqlResource,
  getWorkflows,
  getWorkflow,
  getWebApps,
  getWebApp,
  getView,
  getViews,
  getMaterializedView,
  getMaterializedViews,
} from "./dmv2";

export {
  ClickHousePrecision,
  ClickHouseDecimal,
  ClickHouseByteSize,
  ClickHouseFixedStringSize,
  ClickHouseFloat,
  ClickHouseInt,
  ClickHouseJson,
  LowCardinality,
  ClickHouseNamedTuple,
  ClickHouseDefault,
  ClickHouseTTL,
  ClickHouseMaterialized,
  WithDefault,
  ClickHouseCodec,
  // Added friendly aliases and numeric helpers
  DateTime,
  DateTime64,
  DateTimeString,
  DateTime64String,
  FixedString,
  Float32,
  Float64,
  Int8,
  Int16,
  Int32,
  Int64,
  UInt8,
  UInt16,
  UInt32,
  UInt64,
  Decimal,
} from "./dataModels/types";

export type { ApiUtil, ConsumptionUtil } from "./consumption-apis/helpers";

export * from "./sqlHelpers";
